name: Docs - Doxygen and MkDocs

on:
  push:
    branches: [ main ]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install documentation tools
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          pip install mkdocs mkdocs-material

      - name: Generate Doxygen
        run: |
          if [ -f "Doxyfile" ]; then
            doxygen Doxyfile
          else
            echo "No Doxyfile found, skipping Doxygen."
          fi

      - name: Build MkDocs
        run: |
          if [ -f "mkdocs.yml" ]; then
            mkdocs build --site-dir public
          else
            echo "No mkdocs.yml found, skipping MkDocs."
          fi

      - name: Deploy to GitHub Pages
        if: success() && (hashFiles('public/**') != '' || hashFiles('docs/html/**') != '')
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public # Adjust based on where files are
